Repository fairnesscoop/permacoop, pull requests merged in 2020-05, with the labels that each got.

#94 [client] Move components
  client/src/components/Breadcrumb.svelte
  client/src/components/Footer.svelte
  client/src/components/Loader.svelte
  client/src/components/Nav.svelte
  client/src/components/SecuredLink.svelte
  client/src/components/SecuredView.svelte
  client/src/components/ServerErrors.svelte
  client/src/components/inputs/CustomersInput.svelte
  client/src/components/inputs/MonthsInput.svelte
  client/src/components/inputs/ProjectsInput.svelte
  client/src/components/inputs/TasksInput.svelte
  client/src/components/inputs/UsersInput.svelte
  client/src/routes/_layout.svelte
  client/src/routes/accounting/daily_rates/[id].edit.svelte
  client/src/routes/accounting/daily_rates/_Form.svelte
  client/src/routes/accounting/daily_rates/add.svelte
  client/src/routes/accounting/daily_rates/index.svelte
  client/src/routes/accounting/pay_stubs/_Form.svelte
  client/src/routes/accounting/pay_stubs/add.svelte
  client/src/routes/accounting/pay_stubs/index.svelte
  client/src/routes/accounting/quotes/_Form.svelte
  client/src/routes/accounting/quotes/add.svelte
  client/src/routes/accounting/quotes/index.svelte
  client/src/routes/customers/[id].edit.svelte
  client/src/routes/customers/add.svelte
  client/src/routes/customers/index.svelte
  client/src/routes/faircalendar/[date].add.svelte
  client/src/routes/faircalendar/[id].edit.svelte
  client/src/routes/faircalendar/_Filters.svelte
  client/src/routes/faircalendar/_Form.svelte
  client/src/routes/faircalendar/index.svelte
  client/src/routes/login/index.svelte
  client/src/routes/profile/index.svelte
  client/src/routes/projects/[id].edit.svelte
  client/src/routes/projects/_Form.svelte
  client/src/routes/projects/add.svelte
  client/src/routes/projects/index.svelte
  client/src/routes/tasks/[id].edit.svelte
  client/src/routes/tasks/add.svelte
  client/src/routes/tasks/index.svelte
  client/src/routes/users/add.svelte
  client/src/routes/users/index.svelte
  server/src/Infrastructure/Adapter/LocalFileStorageAdapter.ts
Labels: technical-task

#95 [client] Use roles constants instead of strings
  client/src/components/Nav.svelte
  client/src/routes/accounting/daily_rates/[id].edit.svelte
  client/src/routes/accounting/daily_rates/add.svelte
  client/src/routes/accounting/daily_rates/index.svelte
  client/src/routes/accounting/pay_stubs/add.svelte
  client/src/routes/accounting/pay_stubs/index.svelte
  client/src/routes/accounting/quotes/add.svelte
  client/src/routes/accounting/quotes/index.svelte
  client/src/routes/customers/[id].edit.svelte
  client/src/routes/customers/add.svelte
  client/src/routes/customers/index.svelte
  client/src/routes/faircalendar/[date].add.svelte
  client/src/routes/faircalendar/[id].edit.svelte
  client/src/routes/faircalendar/index.svelte
  client/src/routes/projects/[id].edit.svelte
  client/src/routes/projects/_RowDetail.svelte
  client/src/routes/projects/add.svelte
  client/src/routes/projects/index.svelte
  client/src/routes/tasks/[id].edit.svelte
  client/src/routes/tasks/_RowDetail.svelte
  client/src/routes/tasks/add.svelte
  client/src/routes/tasks/index.svelte
  client/src/routes/users/_Form.svelte
  client/src/routes/users/_RowDetail.svelte
  client/src/routes/users/add.svelte
  client/src/routes/users/index.svelte
  client/src/utils/roles.js
Labels: technical-task

#97 [client] Move role constants
  client/src/components/Nav.svelte
  client/src/constants/roles.js
  client/src/routes/accounting/daily_rates/[id].edit.svelte
  client/src/routes/accounting/daily_rates/add.svelte
  client/src/routes/accounting/daily_rates/index.svelte
  client/src/routes/accounting/pay_stubs/add.svelte
  client/src/routes/accounting/pay_stubs/index.svelte
  client/src/routes/accounting/quotes/add.svelte
  client/src/routes/accounting/quotes/index.svelte
  client/src/routes/customers/[id].edit.svelte
  client/src/routes/customers/add.svelte
  client/src/routes/customers/index.svelte
  client/src/routes/faircalendar/[date].add.svelte
  client/src/routes/faircalendar/[id].edit.svelte
  client/src/routes/faircalendar/index.svelte
  client/src/routes/projects/[id].edit.svelte
  client/src/routes/projects/add.svelte
  client/src/routes/projects/index.svelte
  client/src/routes/tasks/[id].edit.svelte
  client/src/routes/tasks/add.svelte
  client/src/routes/tasks/index.svelte
  client/src/routes/users/_Form.svelte
  client/src/routes/users/add.svelte
  client/src/routes/users/index.svelte
Labels: technical-task

#98 Change pay stubs domain
  client/src/components/Nav.svelte
  client/src/routes/human_resources/pay_stubs/_Form.svelte
  client/src/routes/human_resources/pay_stubs/add.svelte
  client/src/routes/human_resources/pay_stubs/index.svelte
  server/src/Application/HumanResource/PayStub/CreatePayStubCommand.ts
  server/src/Application/HumanResource/PayStub/CreatePayStubCommandHandler.spec.ts
  server/src/Application/HumanResource/PayStub/CreatePayStubCommandHandler.ts
  server/src/Domain/HumanResource/Exception/PayStubAlreadyExistException.ts
  server/src/Domain/HumanResource/PayStub.entity.spec.ts
  server/src/Domain/HumanResource/PayStub.entity.ts
  server/src/Domain/HumanResource/Repository/IPayStubRepository.ts
  server/src/Domain/HumanResource/Specification/IsPayStubAlreadyExist.spec.ts
  server/src/Domain/HumanResource/Specification/IsPayStubAlreadyExist.ts
  server/src/Infrastructure/Accounting/accounting.module.ts
  server/src/Infrastructure/HumanResource/Action/PayStub/CreatePayStubAction.ts
  server/src/Infrastructure/HumanResource/DTO/PayStubDTO.spec.ts
  server/src/Infrastructure/HumanResource/DTO/PayStubDTO.ts
  server/src/Infrastructure/HumanResource/Repository/PayStubRepository.ts
  server/src/Infrastructure/HumanResource/humanResource.module.ts
  server/src/app.module.ts
Labels: technical-task

#99 Move paystubs
  client/src/components/Nav.svelte
  client/src/components/inputs/UsersInput.svelte
  client/src/routes/human_resources/users/_Form.svelte
  client/src/routes/human_resources/users/add.svelte
  client/src/routes/human_resources/users/index.svelte
  client/src/routes/users/add.svelte
  server/src/Application/PayStub/Command/CreatePayStubCommand.ts
  server/src/Application/PayStub/Command/CreatePayStubCommandHandler.spec.ts
  server/src/Application/PayStub/Command/CreatePayStubCommandHandler.ts
  server/src/Domain/PayStub/Exception/PayStubAlreadyExistException.ts
  server/src/Domain/PayStub/PayStub.entity.spec.ts
  server/src/Domain/PayStub/PayStub.entity.ts
  server/src/Domain/PayStub/Repository/IPayStubRepository.ts
  server/src/Domain/PayStub/Specification/IsPayStubAlreadyExist.spec.ts
  server/src/Domain/PayStub/Specification/IsPayStubAlreadyExist.ts
  server/src/Infrastructure/PayStub/Action/PayStub/CreatePayStubAction.ts
  server/src/Infrastructure/PayStub/DTO/PayStubDTO.spec.ts
  server/src/Infrastructure/PayStub/DTO/PayStubDTO.ts
  server/src/Infrastructure/PayStub/Repository/PayStubRepository.ts
  server/src/Infrastructure/PayStub/payStub.module.ts
  server/src/app.module.ts
Labels: technical-task

#101 [server] User administrative
  server/migrations/1588426949796-UserAdministrative.ts
  server/src/Application/Accounting/Command/DailyRate/CreateDailyRateCommandHandler.spec.ts
  server/src/Application/Accounting/Command/DailyRate/CreateDailyRateCommandHandler.ts
  server/src/Application/Accounting/Command/DailyRate/UpdateDailyRateCommandHandler.spec.ts
  server/src/Application/Accounting/Command/DailyRate/UpdateDailyRateCommandHandler.ts
  server/src/Application/Accounting/Command/Quote/CreateQuoteItemsCommandHandler.spec.ts
  server/src/Application/Accounting/Command/Quote/CreateQuoteItemsCommandHandler.ts
  server/src/Application/Accounting/Query/DailyRate/GetDailyRateByIdQueryHandler.spec.ts
  server/src/Application/Accounting/Query/DailyRate/GetDailyRateByIdQueryHandler.ts
  server/src/Application/Accounting/Query/DailyRate/GetDailyRatesQueryHandler.spec.ts
  server/src/Application/Accounting/Query/DailyRate/GetDailyRatesQueryHandler.ts
  server/src/Application/FairCalendar/Query/GetMonthlyEventsQueryHandler.spec.ts
  server/src/Application/FairCalendar/Query/GetMonthlyEventsQueryHandler.ts
  server/src/Application/HumanResource/User/Command/CreateUserCommand.ts
  server/src/Application/HumanResource/User/Command/CreateUserCommandHandler.spec.ts
  server/src/Application/HumanResource/User/Command/CreateUserCommandHandler.ts
  server/src/Application/HumanResource/User/Query/GetUserByIdQueryHandler.spec.ts
  server/src/Application/HumanResource/User/Query/GetUserByIdQueryHandler.ts
  server/src/Application/HumanResource/User/Query/GetUsersQueryHandler.spec.ts
  server/src/Application/HumanResource/User/Query/GetUsersQueryHandler.ts
  server/src/Application/HumanResource/User/View/UserView.ts
  server/src/Domain/Accounting/DailyRate.entity.spec.ts
  server/src/Domain/Accounting/DailyRate.entity.ts
  server/src/Domain/Accounting/QuoteItem.entity.spec.ts
  server/src/Domain/Accounting/QuoteItem.entity.ts
  server/src/Domain/FairCalendar/Event.entity.spec.ts
  server/src/Domain/FairCalendar/Event.entity.ts
  server/src/Domain/FairCalendar/GetEventsOverview.spec.ts
  server/src/Domain/FairCalendar/GetEventsOverview.ts
  server/src/Domain/HumanResource/User/Exception/EntryDateMissingException.ts
  server/src/Domain/HumanResource/User/Exception/UserAdministrativeMissingException.ts
  server/src/Domain/HumanResource/User/Repository/IUserAdministrativeRepository.ts
  server/src/Domain/HumanResource/User/Specification/IsEmailAlreadyExist.spec.ts
  server/src/Domain/HumanResource/User/User.entity.spec.ts
  server/src/Domain/HumanResource/User/User.entity.ts
  server/src/Domain/HumanResource/User/UserAdministrative.entity.spec.ts
  server/src/Domain/HumanResource/User/UserAdministrative.entity.ts
  server/src/Infrastructure/HumanResource/PayStub/Action/PayStub/CreatePayStubAction.ts
  server/src/Infrastructure/HumanResource/User/Action/CreateUserAction.ts
  server/src/Infrastructure/HumanResource/User/Action/GetMeAction.ts
  server/src/Infrastructure/HumanResource/User/Action/GetUsersAction.ts
  server/src/Infrastructure/HumanResource/User/Action/LoginAction.ts
  server/src/Infrastructure/HumanResource/User/Action/UpdateMeAction.ts
  server/src/Infrastructure/HumanResource/User/DTO/UserAdministrativeDTO.spec.ts
  server/src/Infrastructure/HumanResource/User/DTO/UserAdministrativeDTO.ts
  server/src/Infrastructure/HumanResource/User/DTO/UserDTO.spec.ts
  server/src/Infrastructure/HumanResource/User/DTO/UserDTO.ts
  server/src/Infrastructure/HumanResource/User/Repository/UserAdministrativeRepository.ts
  server/src/Infrastructure/HumanResource/User/Repository/UserRepository.ts
  server/src/Infrastructure/HumanResource/User/Security/BearerStrategy.spec.ts
  server/src/Infrastructure/HumanResource/humanResource.module.ts
Labels: ready-to-review

#102 [client] User administrative
  client/package-lock.json
  client/package.json
  client/src/components/inputs/CustomersInput.svelte
  client/src/components/inputs/DateInput.svelte
  client/src/components/inputs/EmailInput.svelte
  client/src/components/inputs/MoneyInput.svelte
  client/src/components/inputs/PasswordInput.svelte
  client/src/components/inputs/ProjectsInput.svelte
  client/src/components/inputs/SelectInput.svelte
  client/src/components/inputs/TasksInput.svelte
  client/src/components/inputs/TextInput.svelte
  client/src/components/inputs/UsersInput.svelte
  client/src/routes/accounting/daily_rates/_Form.svelte
  client/src/routes/accounting/quotes/_Form.svelte
  client/src/routes/accounting/quotes/index.svelte
  client/src/routes/customers/_Form.svelte
  client/src/routes/faircalendar/_Form.svelte
  client/src/routes/human_resources/pay_stubs/_Form.svelte
  client/src/routes/human_resources/users/_Form.svelte
  client/src/routes/human_resources/users/_UserAdministrativeForm.svelte
  client/src/routes/human_resources/users/index.svelte
  client/src/routes/login/index.svelte
  client/src/routes/profile/_Form.svelte
  client/src/routes/projects/_Form.svelte
  client/src/routes/tasks/_Form.svelte
  client/static/css/permacoop.css
  server/src/Application/Accounting/Command/DailyRate/CreateDailyRateCommandHandler.spec.ts
  server/src/Application/Accounting/Command/DailyRate/CreateDailyRateCommandHandler.ts
  server/src/Application/Accounting/Command/DailyRate/UpdateDailyRateCommandHandler.spec.ts
  server/src/Application/Accounting/Command/DailyRate/UpdateDailyRateCommandHandler.ts
  server/src/Application/Accounting/Command/Quote/CreateQuoteItemsCommandHandler.spec.ts
  server/src/Application/Accounting/Command/Quote/CreateQuoteItemsCommandHandler.ts
  server/src/Application/Accounting/Query/DailyRate/GetDailyRateByIdQueryHandler.spec.ts
  server/src/Application/Accounting/Query/DailyRate/GetDailyRateByIdQueryHandler.ts
  server/src/Application/Accounting/Query/DailyRate/GetDailyRatesQueryHandler.spec.ts
  server/src/Application/Accounting/Query/DailyRate/GetDailyRatesQueryHandler.ts
  server/src/Application/Accounting/Query/Quote/GetQuotesQueryHandler.spec.ts
  server/src/Application/Accounting/Query/Quote/GetQuotesQueryHandler.ts
  server/src/Application/HumanResource/User/Command/CreateUserCommandHandler.spec.ts
  server/src/Application/HumanResource/User/Command/CreateUserCommandHandler.ts
  server/src/Domain/Accounting/DailyRate.entity.spec.ts
  server/src/Domain/Accounting/DailyRate.entity.ts
  server/src/Domain/Accounting/QuoteItem.entity.spec.ts
  server/src/Domain/Accounting/QuoteItem.entity.ts
  server/src/Domain/HumanResource/User/UserAdministrative.entity.spec.ts
  server/src/Domain/HumanResource/User/UserAdministrative.entity.ts
Labels: ready-to-review

#103 List pay stubs
  client/package-lock.json
  client/package.json
  client/src/components/Nav.svelte
  client/src/routes/human_resources/pay_stubs/_Form.svelte
  client/src/routes/human_resources/pay_stubs/index.svelte
  server/src/Application/File/View/FileView.ts
  server/src/Application/HumanResource/PayStub/Query/GetPayStubsQuery.ts
  server/src/Application/HumanResource/PayStub/Query/GetPayStubsQueryHandler.spec.ts
  server/src/Application/HumanResource/PayStub/Query/GetPayStubsQueryHandler.ts
  server/src/Application/HumanResource/PayStub/View/PayStubView.ts
  server/src/Domain/File/File.entity.spec.ts
  server/src/Domain/File/File.entity.ts
  server/src/Domain/HumanResource/PayStub/Repository/IPayStubRepository.ts
  server/src/Infrastructure/HumanResource/PayStub/Action/PayStub/GetPayStubsAction.ts
  server/src/Infrastructure/HumanResource/PayStub/Repository/PayStubRepository.ts
  server/src/Infrastructure/HumanResource/humanResource.module.ts
Labels: ready-to-review

#105 [server/client] Download payslip
  client/src/routes/human_resources/pay_slips/index.svelte
  client/src/utils/downloadFile.js
  server/src/Application/File/Command/DownloadFileCommandHandler.spec.ts
  server/src/Application/File/Command/DownloadFileQuery.ts
  server/src/Application/File/Command/DownloadFileQueryHandler.ts
  server/src/Application/File/Command/UploadFileCommandHandler.spec.ts
  server/src/Application/File/Command/UploadFileCommandHandler.ts
  server/src/Application/File/View/DownloadedFileView.ts
  server/src/Application/HumanResource/PaySlip/Command/CreatePaySlipCommandHandler.spec.ts
  server/src/Application/HumanResource/PaySlip/Query/GetPaySlipByIdQuery.ts
  server/src/Application/HumanResource/PaySlip/Query/GetPaySlipByIdQueryHandler.spec.ts
  server/src/Application/HumanResource/PaySlip/Query/GetPaySlipByIdQueryHandler.ts
  server/src/Application/IFileStorage.ts
  server/src/Domain/File/File.entity.spec.ts
  server/src/Domain/File/File.entity.ts
  server/src/Domain/HumanResource/PaySlip/Exception/PaySlipAlreadyExistException.ts
  server/src/Domain/HumanResource/PaySlip/Exception/PaySlipNotFoundException.ts
  server/src/Domain/HumanResource/PaySlip/Repository/IPaySlipRepository.ts
  server/src/Infrastructure/Adapter/LocalFileStorageAdapter.ts
  server/src/Infrastructure/File/Repository/FileRepository.ts
  server/src/Infrastructure/File/file.module.ts
  server/src/Infrastructure/HumanResource/PaySlip/Action/DownloadPaySlipAction.ts
  server/src/Infrastructure/HumanResource/PaySlip/Repository/PaySlipRepository.ts
  server/src/Infrastructure/HumanResource/humanResource.module.ts
Labels: ready-to-review

#107 [server/client] Add holiday
  README.md
  client/src/components/Nav.svelte
  client/src/routes/human_resources/holidays/_Form.svelte
  client/src/routes/human_resources/holidays/add.svelte
  client/src/routes/human_resources/holidays/index.svelte
  server/migrations/1588872587472-Holiday.ts
  server/src/Application/File/Query/DownloadFileQueryHandler.spec.ts
  server/src/Application/HumanResource/Holiday/Command/CreateHolidayCommand.ts
  server/src/Application/HumanResource/Holiday/Command/CreateHolidayCommandHandler.spec.ts
  server/src/Application/HumanResource/Holiday/Command/CreateHolidayCommandHandler.ts
  server/src/Domain/HumanResource/Holiday/Exception/HolidayAlreadyExistForThisPeriodException.ts
  server/src/Domain/HumanResource/Holiday/Holiday.entity.spec.ts
  server/src/Domain/HumanResource/Holiday/Holiday.entity.ts
  server/src/Domain/HumanResource/Holiday/Repository/IHolidayRepository.ts
  server/src/Domain/HumanResource/Holiday/Specification/DoesHolidayExistForPeriod.spec.ts
  server/src/Domain/HumanResource/Holiday/Specification/DoesHolidayExistForPeriod.ts
  server/src/Infrastructure/Common/Validator/DateGreaterOrEqualThan.ts
  server/src/Infrastructure/HumanResource/Holiday/Action/CreateHolidayAction.ts
  server/src/Infrastructure/HumanResource/Holiday/DTO/HolidayDTO.spec.ts
  server/src/Infrastructure/HumanResource/Holiday/DTO/HolidayDTO.ts
  server/src/Infrastructure/HumanResource/Holiday/Repository/HolidayRepository.ts
  server/src/Infrastructure/HumanResource/humanResource.module.ts
Labels: ready-to-review

#109 [server] Refuse holiday
  server/migrations/1588872587472-Holiday.ts
  server/src/Application/HumanResource/Holiday/Command/RefuseHolidayCommand.ts
  server/src/Application/HumanResource/Holiday/Command/RefuseHolidayCommandHandler.spec.ts
  server/src/Application/HumanResource/Holiday/Command/RefuseHolidayCommandHandler.ts
  server/src/Application/IDateUtils.ts
  server/src/Domain/File/Strategy/FileDirectoryStrategy.spec.ts
  server/src/Domain/HumanResource/Holiday/Exception/HolidayCantBeModeratedException.ts
  server/src/Domain/HumanResource/Holiday/Exception/HolidayNotFoundException.ts
  server/src/Domain/HumanResource/Holiday/Holiday.entity.spec.ts
  server/src/Domain/HumanResource/Holiday/Holiday.entity.ts
  server/src/Domain/HumanResource/Holiday/Repository/IHolidayRepository.ts
  server/src/Domain/HumanResource/Holiday/Specification/CanHolidayBeModerated.spec.ts
  server/src/Domain/HumanResource/Holiday/Specification/CanHolidayBeModerated.ts
  server/src/Infrastructure/Accounting/accounting.module.ts
  server/src/Infrastructure/Adapter/DateUtilsAdapter.spec.ts
  server/src/Infrastructure/Adapter/DateUtilsAdapter.ts
  server/src/Infrastructure/FairCalendar/faircalendar.module.ts
  server/src/Infrastructure/File/file.module.ts
  server/src/Infrastructure/HumanResource/Holiday/Action/RefuseHolidayAction.ts
  server/src/Infrastructure/HumanResource/Holiday/DTO/ModerationDTO.spec.ts
  server/src/Infrastructure/HumanResource/Holiday/DTO/ModerationDTO.ts
  server/src/Infrastructure/HumanResource/Holiday/Repository/HolidayRepository.ts
  server/src/Infrastructure/HumanResource/humanResource.module.ts
Labels: ready-to-review

#110 Fix unit test
  client/package-lock.json
  client/package.json
  client/src/components/Breadcrumb.spec.js
  client/src/components/Breadcrumb.svelte
  client/src/components/Footer.spec.js
  client/src/components/Loader.spec.js
  client/src/components/Loader.svelte
  client/src/components/Nav.spec.js
  client/src/components/Nav.svelte
  client/src/components/SecuredLink.spec.js
  client/src/components/SecuredView.spec.js
  client/src/components/ServerErrors.spec.js
Labels: ready-to-review

#111 [Client] Add unit test on client
  client/rollup.config.js
  client/src/components/Breadcrumb.spec.js
  client/src/components/Footer.spec.js
  client/src/components/Loader.spec.js
  client/src/components/Nav.spec.js
  client/src/components/SecuredLink.spec.js
  client/src/components/SecuredView.spec.js
  client/src/components/ServerErrors.spec.js
  client/src/components/inputs/CustomersInput.spec.js
  client/src/components/inputs/EmailInput.spec.js
  client/src/components/inputs/EmailInput.svelte
  client/src/components/inputs/MoneyInput.spec.js
  client/src/components/inputs/MoneyInput.svelte
  client/src/components/inputs/PasswordInput.svelte
  client/src/components/inputs/ProjectsInput.spec.js
  client/src/components/inputs/SelectInput.spec.js
  client/src/components/inputs/SelectInput.svelte
  client/src/components/inputs/TasksInput.spec.js
  client/src/components/inputs/TextInput.spec.js
  client/src/components/inputs/TextInput.svelte
  client/src/components/inputs/UsersInput.spec.js
  client/src/utils/shortid.js
Labels: ready-to-review

#112 [server] Accept holiday
  server/src/Application/HumanResource/Holiday/Command/AcceptHolidayCommand.ts
  server/src/Application/HumanResource/Holiday/Command/AcceptHolidayCommandHandler.spec.ts
  server/src/Application/HumanResource/Holiday/Command/AcceptHolidayCommandHandler.ts
  server/src/Application/HumanResource/Holiday/Event/AcceptedHolidayEvent.ts
  server/src/Application/HumanResource/Holiday/Event/AcceptedHolidayEventListener.spec.ts
  server/src/Application/HumanResource/Holiday/Event/AcceptedHolidayEventListener.ts
  server/src/Application/IDateUtils.ts
  server/src/Application/IEvent.ts
  server/src/Application/IEventBus.ts
  server/src/Domain/FairCalendar/Converter/HolidayToEventsConverter.spec.ts
  server/src/Domain/FairCalendar/Converter/HolidayToEventsConverter.ts
  server/src/Domain/FairCalendar/Repository/IEventRepository.ts
  server/src/Domain/HumanResource/Holiday/Holiday.entity.spec.ts
  server/src/Domain/HumanResource/Holiday/Holiday.entity.ts
  server/src/Infrastructure/Adapter/DateUtilsAdapter.spec.ts
  server/src/Infrastructure/Adapter/DateUtilsAdapter.ts
  server/src/Infrastructure/Adapter/EventBusAdapter.ts
  server/src/Infrastructure/HumanResource/Holiday/Action/AcceptHolidayAction.ts
  server/src/Infrastructure/HumanResource/humanResource.module.ts
  server/src/Infrastructure/bus.module.ts
Labels: ready-to-review

#114 [server] Lists pagination
  server/src/Application/Accounting/Query/DailyRate/GetDailyRatesQuery.ts
  server/src/Application/Accounting/Query/DailyRate/GetDailyRatesQueryHandler.spec.ts
  server/src/Application/Accounting/Query/DailyRate/GetDailyRatesQueryHandler.ts
  server/src/Application/Accounting/Query/Quote/GetQuotesQuery.ts
  server/src/Application/Accounting/Query/Quote/GetQuotesQueryHandler.spec.ts
  server/src/Application/Accounting/Query/Quote/GetQuotesQueryHandler.ts
  server/src/Application/Common/Pagination.ts
  server/src/Application/Customer/Query/GetCustomersQuery.ts
  server/src/Application/Customer/Query/GetCustomersQueryHandler.spec.ts
  server/src/Application/Customer/Query/GetCustomersQueryHandler.ts
  server/src/Application/HumanResource/PaySlip/Query/GetPaySlipsQuery.ts
  server/src/Application/HumanResource/PaySlip/Query/GetPaySlipsQueryHandler.spec.ts
  server/src/Application/HumanResource/PaySlip/Query/GetPaySlipsQueryHandler.ts
  server/src/Application/Project/Query/GetProjectsQuery.ts
  server/src/Application/Project/Query/GetProjectsQueryHandler.spec.ts
  server/src/Application/Project/Query/GetProjectsQueryHandler.ts
  server/src/Application/Task/Query/GetTasksQuery.ts
  server/src/Application/Task/Query/GetTasksQueryHandler.spec.ts
  server/src/Application/Task/Query/GetTasksQueryHandler.ts
  server/src/Domain/Accounting/Repository/IDailyRateRepository.ts
  server/src/Domain/Accounting/Repository/IQuoteRepository.ts
  server/src/Domain/Customer/Repository/ICustomerRepository.ts
  server/src/Domain/HumanResource/PaySlip/Repository/IPaySlipRepository.ts
  server/src/Domain/Project/Repository/IProjectRepository.ts
  server/src/Domain/Task/Repository/ITaskRepository.ts
  server/src/Infrastructure/Accounting/Action/DailyRate/GetDailyRatesAction.ts
  server/src/Infrastructure/Accounting/Action/Quote/GetQuotesAction.ts
  server/src/Infrastructure/Accounting/Repository/DailyRateRepository.ts
  server/src/Infrastructure/Accounting/Repository/QuoteRepository.ts
  server/src/Infrastructure/Common/DTO/PaginationDTO.spec.ts
  server/src/Infrastructure/Common/DTO/PaginationDTO.ts
  server/src/Infrastructure/Customer/Action/GetCustomersAction.ts
  server/src/Infrastructure/Customer/Repository/CustomerRepository.ts
  server/src/Infrastructure/HumanResource/PaySlip/Action/GetPaySlipsAction.ts
  server/src/Infrastructure/HumanResource/PaySlip/Repository/PaySlipRepository.ts
  server/src/Infrastructure/Project/Action/GetProjectsAction.ts
  server/src/Infrastructure/Project/DTO/FiltersDTO.spec.ts
  server/src/Infrastructure/Project/DTO/FiltersDTO.ts
  server/src/Infrastructure/Project/Repository/ProjectRepository.ts
  server/src/Infrastructure/Task/Action/GetTasksAction.ts
  server/src/Infrastructure/Task/Repository/TaskRepository.ts
Labels: ready-to-review

#115 [client] Lists pagination
  client/src/components/Pagination.svelte
  client/src/routes/accounting/daily_rates/_Form.svelte
  client/src/routes/accounting/daily_rates/_Table.svelte
  client/src/routes/accounting/daily_rates/index.svelte
  client/src/routes/accounting/quotes/_Form.svelte
  client/src/routes/accounting/quotes/_Table.svelte
  client/src/routes/accounting/quotes/index.svelte
  client/src/routes/customers/_Table.svelte
  client/src/routes/customers/index.svelte
  client/src/routes/faircalendar/_Form.svelte
  client/src/routes/human_resources/pay_slips/_Table.svelte
  client/src/routes/human_resources/pay_slips/index.svelte
  client/src/routes/human_resources/users/_Table.svelte
  client/src/routes/human_resources/users/index.svelte
  client/src/routes/projects/_Form.svelte
  client/src/routes/projects/_Table.svelte
  client/src/routes/projects/index.svelte
  client/src/routes/tasks/_Table.svelte
  client/src/routes/tasks/index.svelte
  client/src/utils/url.js
Labels: ready-to-review

#113 [server] List holidays
  client/src/routes/human_resources/holidays/_Table.svelte
  client/src/routes/human_resources/holidays/index.svelte
  client/static/css/permacoop.css
  server/src/Application/HumanResource/Holiday/Command/AcceptHolidayCommandHandler.spec.ts
  server/src/Application/HumanResource/Holiday/Command/AcceptHolidayCommandHandler.ts
  server/src/Application/HumanResource/Holiday/Command/CreateHolidayCommandHandler.spec.ts
  server/src/Application/HumanResource/Holiday/Command/CreateHolidayCommandHandler.ts
  server/src/Application/HumanResource/Holiday/Query/GetHolidaysQuery.ts
  server/src/Application/HumanResource/Holiday/Query/GetHolidaysQueryHandler.spec.ts
  server/src/Application/HumanResource/Holiday/Query/GetHolidaysQueryHandler.ts
  server/src/Application/HumanResource/Holiday/View/HolidayView.ts
  server/src/Domain/FairCalendar/Exception/EventsAlreadyExistForThisPeriodException.ts
  server/src/Domain/FairCalendar/Repository/IEventRepository.ts
  server/src/Domain/FairCalendar/Specification/DoesEventsExistForPeriod.spec.ts
  server/src/Domain/FairCalendar/Specification/DoesEventsExistForPeriod.ts
  server/src/Domain/HumanResource/Holiday/Repository/IHolidayRepository.ts
  server/src/Infrastructure/FairCalendar/Repository/EventRepository.ts
  server/src/Infrastructure/HumanResource/Holiday/Action/CreateHolidayAction.ts
  server/src/Infrastructure/HumanResource/Holiday/Action/GetHolidaysAction.ts
  server/src/Infrastructure/HumanResource/Holiday/Repository/HolidayRepository.ts
  server/src/Infrastructure/HumanResource/User/Action/CreateUserAction.ts
  server/src/Infrastructure/HumanResource/User/Action/GetUsersAction.ts
  server/src/Infrastructure/HumanResource/humanResource.module.ts
Labels: ready-to-review

#116 Improve docker setup
  Makefile
  README.md
  docker-compose.yml
Labels: ops, ready-to-review
